language: node_js
node_js:
- 8
- node
- 6
- 4
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
install: yarn

script:
- yarn prebuild
- yarn test --coverage

cache:
  yarn: true

branches:
  only:
  - master
